import { Preset } from '../types';

export const PRESETS: Preset[] = [
  {
    id: 'vintage-dots',
    name: 'Фото-растр (Газетний)',
    description: 'Класичний газетний растр 45° з плавними півтонами для фотографій',
    halftone: {
      mode: 'dots',
      contrast: 45,
      dotSize: 6.5,
    },
    tornEdge: {
      enabled: true,
      padding: 20,
      roughness: 3,
      canvasPadding: 0,
      frequency: 0.07,
      octaves: 3,
      paperColor: '#ffffff',
      paperTexture: true,
      dropShadow: true,
      shadowBlur: 50,
      shadowOpacity: 0.28,
    },
  },
  {
    id: 'color-halftone',
    name: 'Колір + Растр (Кольоровий)',
    description: 'Збереження насичених кольорів фотографії з текстурою газетного растру',
    halftone: {
      mode: 'color-halftone',
      contrast: 45,
      dotSize: 6.5,
    },
    tornEdge: {
      enabled: true,
      padding: 20,
      roughness: 3,
      canvasPadding: 0,
      frequency: 0.07,
      octaves: 3,
      paperColor: '#ffffff',
      paperTexture: true,
      dropShadow: true,
      shadowBlur: 50,
      shadowOpacity: 0.28,
    },
  },
  {
    id: 'graphic-dots',
    name: 'Графічний растр (Лінійний)',
    description: 'Чіткі розділені цятки для графіки, логотипів, артів та тексту',
    halftone: {
      mode: 'graphic-dots',
      contrast: 50,
      dotSize: 6.5,
    },
    tornEdge: {
      enabled: true,
      padding: 20,
      roughness: 3,
      canvasPadding: 0,
      frequency: 0.07,
      octaves: 3,
      paperColor: '#ffffff',
      paperTexture: true,
      dropShadow: true,
      shadowBlur: 50,
      shadowOpacity: 0.28,
    },
  },
  {
    id: 'paper-halftone-vintage',
    name: 'Паперовий растр (Paper Halftone)',
    description: 'Графічний растр із фоном та текстурою паперової підкладки',
    halftone: {
      mode: 'paper-halftone',
      contrast: 50,
      dotSize: 6,
    },
    tornEdge: {
      enabled: true,
      padding: 20,
      roughness: 3,
      canvasPadding: 0,
      frequency: 0.07,
      octaves: 3,
      paperColor: '#f6f0db',
      paperTexture: true,
      dropShadow: true,
      shadowBlur: 50,
      shadowOpacity: 0.3,
    },
  }
];
