import { Preset } from '../types';

export const PRESETS: Preset[] = [
  {
    id: 'grayscale-rich',
    name: 'Контрастне ч/б (Grayscale)',
    description: 'Глибокі тіні та плавні відтінки сірого з білим рваним контуром',
    halftone: {
      mode: 'grayscale-contrast',
      contrast: 50,
      dotSize: 6,
      invert: false,
    },
    tornEdge: {
      enabled: true,
      padding: 24,
      roughness: 14,
      canvasPadding: 0,
      frequency: 0.07,
      octaves: 3,
      paperColor: '#ffffff',
      paperTexture: true,
      dropShadow: true,
      shadowBlur: 18,
      shadowOpacity: 0.3,
    },
  },
  {
    id: 'vintage-dots',
    name: 'Фото-растр (Газетний)',
    description: 'Класичний газетний растр 45° з плавними півтонами для фотографій',
    halftone: {
      mode: 'dots',
      contrast: 45,
      dotSize: 6.5,
      invert: false,
    },
    tornEdge: {
      enabled: true,
      padding: 22,
      roughness: 14,
      canvasPadding: 0,
      frequency: 0.07,
      octaves: 3,
      paperColor: '#ffffff',
      paperTexture: true,
      dropShadow: true,
      shadowBlur: 16,
      shadowOpacity: 0.28,
    },
  },
  {
    id: 'graphic-dots',
    name: 'Графічний растр (Лінійний)',
    description: 'Чіткі розділені цятки для графіки, логотипів, артів та тексту',
    halftone: {
      mode: 'graphic-dots',
      contrast: 50,
      dotSize: 6.5,
      invert: false,
    },
    tornEdge: {
      enabled: true,
      padding: 22,
      roughness: 14,
      canvasPadding: 0,
      frequency: 0.07,
      octaves: 3,
      paperColor: '#ffffff',
      paperTexture: true,
      dropShadow: true,
      shadowBlur: 16,
      shadowOpacity: 0.28,
    },
  },
  {
    id: 'hybrid-newsprint',
    name: 'Фото + Растр (Гібрид)',
    description: 'Півтони фотографії з накладанням текстури газетного растру',
    halftone: {
      mode: 'hybrid',
      contrast: 45,
      dotSize: 6,
      invert: false,
    },
    tornEdge: {
      enabled: true,
      padding: 24,
      roughness: 15,
      canvasPadding: 0,
      frequency: 0.07,
      octaves: 3,
      paperColor: '#ffffff',
      paperTexture: true,
      dropShadow: true,
      shadowBlur: 18,
      shadowOpacity: 0.3,
    },
  },
  {
    id: 'retro-engraving',
    name: 'Ретро-гравюра (Engraving)',
    description: 'Ефект гравюри з хвилястими штрихами',
    halftone: {
      mode: 'engraving',
      contrast: 50,
      dotSize: 6,
      invert: false,
    },
    tornEdge: {
      enabled: true,
      padding: 20,
      roughness: 12,
      canvasPadding: 0,
      frequency: 0.06,
      octaves: 3,
      paperColor: '#fcf8f2',
      paperTexture: true,
      dropShadow: true,
      shadowBlur: 14,
      shadowOpacity: 0.25,
    },
  }
];
